### ISSUE TITLE
before change component how we can clear toast?

### ISSUE THREAD

**Issue by yasir-rafiq** [Vashnak/react-toasts#9]
Clear toast component before changing route.
Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method

**Comment by Vashnak** [comment]
I will take a look soon

**Comment by Vashnak** [comment]
I published a new version : 3.0.1
It should be resolved. Can you confirm it to me ?

**Comment by jvink** [comment]
Not resolved yet.

**Comment by jvink** [comment]
Error still persists when unmounting the component. So not just when changing route.

**Comment by Vashnak** [comment]
Okay, I found the bug, this time it should be really fixed on the version 3.0.2, I wait your confirmation before closing the issue

**Comment by jvink** [comment]
Yep it's fixed. Thanks!

**Comment by Vashnak** [comment]
Thank you both for your help !
